import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,AtSign,ChevronRight,Focus,Info,Languages,Layers3,Maximize2,Minimize2,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {t,useLocale,localizedName,secondaryName,type Locale} from './i18n';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,EXPLANATIONS_ZH,explanation,systemName,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const SUGGESTIONS=['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'];
/** Common colloquial terms that differ from the standard anatomical names used in the manifest. */
const QUERY_ALIASES:Record<string,string>={'心脏':'心','大脑':'脑','肝脏':'肝','眼睛':'眼','耳朵':'耳','鼻子':'鼻','舌头':'舌','脖子':'颈','颈部':'颈','屁股':'臀','皮肤':'体被','骨头':'骨','头颅':'颅','脑袋':'脑'};

type TwitterWindow=Window&{twttr?:{widgets:{load:(el?:HTMLElement)=>void}}};
/** X/Twitter timeline embed for the upstream author. The platform script is injected lazily and
    only while this sheet is mounted; if it cannot load (offline, blocked network), a plain link card is shown. */
function XTimeline({locale}:{locale:Locale}){
 const host=useRef<HTMLDivElement>(null),[status,setStatus]=useState<'loading'|'ready'|'failed'>('loading');
 useEffect(()=>{
  let settled=false;
  const w=window as TwitterWindow;
  const settle=(ok:boolean)=>{if(!settled){settled=true;setStatus(ok?'ready':'failed');}};
  const render=()=>{try{w.twttr?.widgets.load(host.current??undefined);}catch{/* Rendering is best-effort. */}};
  if(w.twttr?.widgets){render();settle(true);return;}
  let script=document.querySelector<HTMLScriptElement>('script[data-x-widgets]');
  if(!script){script=document.createElement('script');script.src='https://platform.twitter.com/widgets.js';script.async=true;script.dataset.xWidgets='1';document.head.appendChild(script);}
  script.addEventListener('load',()=>{if(w.twttr?.widgets){render();settle(true);}else settle(false);},{once:true});
  script.addEventListener('error',()=>settle(false),{once:true});
  const timer=setTimeout(()=>settle(!!w.twttr?.widgets),6000);
  return()=>clearTimeout(timer);
 },[]);
 useEffect(()=>{const w=window as TwitterWindow;if(status!=='failed')try{w.twttr?.widgets.load(host.current??undefined);}catch{/* Best-effort. */}},[locale,status]);
 if(status==='failed')return <a className="twitter-fallback" href="https://twitter.com/ashebytes" target="_blank" rel="noreferrer"><AtSign size={16}/><span>{t(locale,'twitterFallback')}</span></a>;
 return <div className={`twitter-embed${status==='loading'?' is-loading':''}`} ref={host}><a className="twitter-timeline" data-height="520" data-chrome="nofooter" data-dnt="true" data-lang={locale==='zh'?'zh-cn':'en'} href="https://twitter.com/ashebytes?ref_src=twsrc%5Etfw">Tweets by @ashebytes</a></div>;
}

export interface ExerciseRecord{id:string;name:string;nameZh:string|null;equipment:string;target:string;targetZh:string|null;secondaryZh:string[];gif:string;image:string;stepsZh:string[];stepsEn:string[]}
export interface ExerciseIndexData{exercises:ExerciseRecord[];byMuscle:Record<string,{exercise:string;role:'primary'|'secondary'}[]>}
const EQUIPMENT_ZH:Record<string,string>={'body weight':'自重',dumbbell:'哑铃',cable:'拉索器',barbell:'杠铃','leverage machine':'综合器械',band:'弹力带','smith machine':'史密斯机',kettlebell:'壶铃',weighted:'负重','stability ball':'稳定球','ez barbell':'曲杆杠铃',assisted:'助力','sled machine':'蹬腿机','medicine ball':'药球',rope:'绳索',roller:'滚轮','resistance band':'阻力带','bosu ball':'波速球','olympic barbell':'奥杠','wheel roller':'健腹轮','trap bar':'六角杠','stationary bike':'动感单车','elliptical machine':'椭圆机','stepmill machine':'爬楼机','skierg machine':'划雪器','upper body ergometer':'上肢功率车',hammer:'铁锤',tire:'轮胎'};

/** Exercise media base. Served from this project's fork of the exercise dataset on GitHub by
    default (works for local dev and deploys alike); override with VITE_EXERCISE_MEDIA, e.g.
    /exercises to use a local clone via the vite plugin, or a CDN/object-storage base. */
const EXERCISE_MEDIA=((import.meta as ImportMeta&{env?:{VITE_EXERCISE_MEDIA?:string}}).env?.VITE_EXERCISE_MEDIA??'https://raw.githubusercontent.com/wuyuan1992/exercises-dataset/main').replace(/\/$/,'');
const mediaUrl=(relative:string)=>`${EXERCISE_MEDIA}/${relative.replace(/^\/+/,'')}`;

/** Training exercises for the selected muscle concept, straight below the muscle title.
    `onExpand` opens the fullscreen view when the poster/GIF is tapped. */
function ExercisePanel({conceptId,locale,index,onExpand}:{conceptId:string;locale:Locale;index:ExerciseIndexData;onExpand:()=>void}){
 const [primaryOnly,setPrimaryOnly]=useState(false),[openId,setOpenId]=useState<string|null>(null);
 const byId=useMemo(()=>new Map(index.exercises.map(e=>[e.id,e])),[index]);
 const all=index.byMuscle[conceptId]??[];
 if(!all.length)return null;
 const list=primaryOnly?all.filter(i=>i.role==='primary'):all;
 return <section className="exercise-panel" aria-label={t(locale,'exercisesTitle')}>
  <div className="exercise-head"><h3>{t(locale,'exercisesTitle')}<span className="small-number">{all.length}</span></h3><Button variant="ghost" className="exercise-filter" aria-pressed={primaryOnly} onClick={()=>setPrimaryOnly(v=>!v)}>{primaryOnly?t(locale,'exercisesPrimary'):t(locale,'exercisesAll')}</Button></div>
  <div className="exercise-list">{list.map(b=>{const ex=byId.get(b.exercise);if(!ex)return null;const expanded=openId===ex.id;const displayName=locale==='zh'?ex.nameZh??ex.name:ex.name;const otherName=locale==='zh'?ex.name:ex.nameZh;const steps=locale==='zh'?ex.stepsZh:ex.stepsEn.length?ex.stepsEn:ex.stepsZh;return <div className={`exercise-item${expanded?' open':''}`} key={ex.id}>
   <Button variant="ghost" className="exercise-row" onClick={()=>setOpenId(expanded?null:ex.id)} aria-expanded={expanded}><img className="exercise-thumb" src={mediaUrl(ex.image)} alt="" loading="lazy" decoding="async"/><span className="exercise-name">{displayName}{otherName&&otherName!==displayName&&<em>{otherName}</em>}{b.role==='secondary'&&<i>{t(locale,'exercisesSecondaryTag')}</i>}</span><span className="exercise-tag">{locale==='zh'?EQUIPMENT_ZH[ex.equipment]??ex.equipment:ex.equipment}</span><ChevronRight size={14}/></Button>
   {expanded&&<div className="exercise-detail"><button type="button" className="exercise-gif-wrap" onClick={onExpand} aria-label={t(locale,'exercisesZoomHint')} title={t(locale,'exercisesZoomHint')}><img className="exercise-gif" src={mediaUrl(ex.gif)} alt={displayName} loading="lazy"/><Maximize2 size={15} className="exercise-zoom-icon"/></button><div className="exercise-detail-copy"><h4 className="exercise-detail-title">{displayName}{otherName&&otherName!==displayName&&<em>{otherName}</em>}</h4>{(ex.targetZh||ex.secondaryZh.length>0)&&<div className="exercise-chips">{ex.targetZh&&<span className="exercise-chip prime">{t(locale,'exercisesPrimary')} · {ex.targetZh}</span>}{ex.secondaryZh.map(g=><span className="exercise-chip" key={g}>{g}</span>)}</div>}<ol className="exercise-steps">{steps.map((s,i)=><li key={i}>{s}</li>)}</ol></div></div>}
  </div>;})}</div>
 </section>;
}
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [locale,toggleLocale]=useLocale();
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[exerciseIndex,setExerciseIndex]=useState<ExerciseIndexData|null>(null),[exerciseLoading,setExerciseLoading]=useState(false),[detailExpanded,setDetailExpanded]=useState(false);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error(t(locale,'catalogueError'));return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 // 首次访问自动展开「来源与范围」;之后仅在用户点击时打开。
 useEffect(()=>{let seen=false;try{seen=!!localStorage.getItem('atlas-about-seen');}catch{/* Private browsing can block storage. */}if(seen)return;const timer=setTimeout(()=>{setAbout(true);try{localStorage.setItem('atlas-about-seen','1');}catch{/* Ignore persistence failures. */}},700);return()=>clearTimeout(timer);},[]);
 // 训练动作索引体积较大,首次打开任何详情时才加载,之后全程复用。
 useEffect(()=>{if(!details||!chosen||exerciseIndex||exerciseLoading)return;setExerciseLoading(true);fetch('/data/exercise-index.json').then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json() as Promise<ExerciseIndexData>;}).then(data=>setExerciseIndex(data)).catch(()=>{/* 非关键数据,静默降级 */}).finally(()=>setExerciseLoading(false));},[details,chosen]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.trim(),lower=term.toLowerCase(),alias=QUERY_ALIASES[term];const suggestions=SUGGESTIONS.map(name=>atlas.concepts.find(c=>c.name===name)).filter((x):x is Concept=>!!x);if(!term)return suggestions;const matchZh=(c:Concept)=>!!c['name-zh']&&(c['name-zh'].includes(term)||!!alias&&c['name-zh'].includes(alias));const score=(c:Concept)=>{const n=localizedName(c,'zh').toLowerCase();return n===lower?3:n.startsWith(lower)?2:!!alias&&(c['name-zh']===alias||!!c['name-zh']&&c['name-zh'].startsWith(alias))?1:0;};return atlas.concepts.filter(c=>c.name.toLowerCase().includes(lower)||c.id.toLowerCase().includes(lower)||matchZh(c)).sort((a,b)=>score(b)-score(a)||a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,'name-zh':p['name-zh'],elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const chosenZh=chosen?.['name-zh']??'',titleSecondary=chosen?(locale==='zh'?chosen.name:chosenZh):'';
 const chosenIsMuscle=!!chosen&&chosen.elements.some(e=>{const p=parts.get(e);return !!p&&(p.system==='muscular'||p.system==='skeletal'||p.system==='connective');});
 const explanationTable=locale==='zh'?EXPLANATIONS_ZH:EXPLANATIONS;
 const views:[View,string][]=[['three-quarter',t(locale,'viewThreeQuarter')],['front',t(locale,'viewFront')],['side',t(locale,'viewSide')],['back',t(locale,'viewBack')]];
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} locale={locale} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {t(locale,'eyebrow')}</div><h1>{t(locale,'title')}<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?t(locale,'identityMeta')(atlas.parts.length.toLocaleString()):t(locale,'identityMeta')('2,234')}</div></header>
  <nav className="top-actions" aria-label={t(locale,'searchAria')}>
   <Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t(locale,'searchAria')}><Search size={18}/><span>{t(locale,'searchButton')}</span><kbd>/</kbd></Button>
   <Button variant="ghost" className="icon-button lang-toggle" onClick={toggleLocale} aria-label={t(locale,'languageAria')} title={t(locale,'languageAria')}><Languages size={18}/><span className="lang-full">{locale==='zh'?'中文':'English'}</span><span className="lang-short">{locale==='zh'?'中':'EN'}</span></Button>
   <Button variant="ghost" className="icon-button" aria-label={t(locale,'aboutAria')} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button>
  </nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={t(locale,'systemsTitle')}>
   <div className="panel-heading"><span>{t(locale,'systemsTitle')}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t(locale,'closeSystems')}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t(locale,'presetAll')}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t(locale,'presetSkeleton')}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t(locale,'presetOrgans')}</Button></div>
   <div className="system-list">{activeSystems.map(s=>{const name=systemName(s,locale);return <div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={t(locale,'showOnly')(name)} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={t(locale,'showSystem')(name)} /></div>})}</div>
   <div className="panel-foot"><span>{t(locale,'piecesVisible')(visibleCount.toLocaleString())}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t(locale,'hideAll')}</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label={t(locale,'searchAria')}><div className="panel-heading"><span>{t(locale,'searchButton')}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t(locale,'closeSearch')}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>localizedName(c,locale)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={t(locale,'searchPlaceholder')} aria-label={t(locale,'searchAriaLabel')} showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t(locale,'noResults')}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{localizedName(c,locale)}{secondaryName(c,locale)&&<em>{secondaryName(c,locale)}</em>}</span><span className="small-number">{t(locale,'pieces')(c.elements.length)}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t(locale,'searchNoteQuery'):t(locale,'searchNoteEmpty')}</p></section>}
  <nav className="view-controls glass" aria-label={t(locale,'cameraControls')}>{views.map((v,i)=><Button variant="ghost" key={v[0]} className={state.view===v[0]?'active':''} aria-pressed={state.view===v[0]} disabled={state.explode>.8&&v[0]!=='front'} onClick={()=>setState(s=>({...s,view:v[0],reset:s.reset+1,rotate:false}))} title={t(locale,'viewAria')(v[1])} aria-label={t(locale,'viewAria')(v[1])}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?t(locale,'pauseAria'):t(locale,'rotateAria')} title={t(locale,'rotateAria')} className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label={t(locale,'resetAria')} title={t(locale,'resetAria')} onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?chosen?localizedName(chosen,locale):t(locale,'captionSelected'):state.explode>.95?t(locale,'captionInventory'):state.explode>.05?t(locale,'captionSeparated'):t(locale,'captionAssembled')}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t(locale,'dockSystems')}><Layers3 size={20}/><span>{t(locale,'dockSystems')}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t(locale,'explodeLabel')}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t(locale,'assembled')}</span><span>{t(locale,'everyPiece')}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t(locale,'dockReset')}><RotateCcw size={18}/><span>{t(locale,'dockReset')}</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?t(locale,'footerPan'):t(locale,'footerOrbit')} <b>·</b> {t(locale,'footerZoom')} <b>·</b> {t(locale,'footerInspect')}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t(locale,'sourceCredits')} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t(locale,'loadingTitle')}</strong><span>{t(locale,'loadingBody')(progress,atlas?.parts.length.toLocaleString()??'2,234')}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>{t(locale,'reload')}</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''} ${detailExpanded?'is-expanded':''}`} showCloseButton={true}><Button variant="ghost" className="icon-button detail-expand" onClick={()=>setDetailExpanded(v=>!v)} aria-label={detailExpanded?t(locale,'detailCollapse'):t(locale,'detailExpand')} title={detailExpanded?t(locale,'detailCollapse'):t(locale,'detailExpand')}>{detailExpanded?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</Button><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?systemName(system,locale):t(locale,'atlasFallback')}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?localizedName(chosen,locale):''}</SheetTitle>{titleSecondary&&<p className="alt-name">{titleSecondary}</p>}</div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}>{chosenIsMuscle&&(exerciseIndex?<ExercisePanel conceptId={chosen!.id} locale={locale} index={exerciseIndex} onExpand={()=>{if(!window.matchMedia('(max-width: 767px)').matches)setDetailExpanded(true);}}/>:exerciseLoading?<div className="exercise-loading">{t(locale,'exercisesLoading')}</div>:null)}<SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system,locale):''}</SheetDescription>{chosen&&!explanationTable[chosen.name.toLowerCase()]&&<span className="context-note">{t(locale,'contextNote')}</span>}<div className="structure-meta"><span>{t(locale,'atlasReference')}<strong>{chosen?.id}</strong></span><span>{t(locale,'selectedPieces')}<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{t(locale,'includedStructures')}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{localizedName(p,locale)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{t(locale,'andMore')(selectedParts.length-50)}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t(locale,'viewSource')} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t(locale,'showSurrounding'):t(locale,'isolate')}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t(locale,'clearSelection')}</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass" aria-describedby={undefined}><div className="eyebrow">{t(locale,'aboutEyebrow')}</div><SheetTitle className="structure-title">{t(locale,'aboutTitle')}</SheetTitle><div className="about-copy"><p><strong>{t(locale,'aboutMaleHeading')}</strong><br/>{t(locale,'aboutMaleBody')}</p><p>{t(locale,'aboutScope1')}</p><p>{t(locale,'aboutScope2')}</p><section className="about-group"><h3>{t(locale,'aboutSourceHeading')}</h3><p>{t(locale,'aboutSourceBody')}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t(locale,'aboutLicenseLink')} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t(locale,'aboutDataLink')} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t(locale,'aboutPublicationLink')} <ArrowUpRight size={14}/></a><p>{t(locale,'creditsExerciseBody')}</p><a href="https://github.com/hasaneyldrm/exercises-dataset" target="_blank" rel="noreferrer">{t(locale,'creditsExerciseLink')} <ArrowUpRight size={14}/></a></section><section className="about-group"><h3>{t(locale,'aboutProjectHeading')}</h3><a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">{t(locale,'creditsRepo')} <ArrowUpRight size={14}/></a><a href="https://human-atlas-seven.vercel.app/" target="_blank" rel="noreferrer">{t(locale,'creditsDemo')} <ArrowUpRight size={14}/></a><XTimeline locale={locale}/></section></div></SheetContent></Sheet>
 </main>;
}
